### ISSUE TITLE
Color command

### ISSUE THREAD

**Issue by Diakarus** [lordjbs/sandboxed#10]
Your color command uses a site created by Alex, owner of KawaiiBot and KawaiiBot Hangout. Did you ask to use this?

**Comment by lordjbs** [comment]
Yeah, I asked him for a color API and he said I could use his.

**Comment by lordjbs** [comment]
(that was some months ago, I'm asking him again right now.)

**Comment by Diakarus** [comment]
I just asked him myself, you're all green

**Comment by AlexFlipnote** [comment]
( ͡° ͜ʖ ͡°)

**Comment by lordjbs** [comment]
:D
